### ISSUE TITLE
login画面が表示されない

### ISSUE THREAD

**Issue by sallop** [masakura/cracker#12]
git init
git clone -b virtual https://github.com/begicra/begicra/
git remote -v
origin    https://github.com/begicra/begicra/ (fetch)
origin    https://github.com/begicra/begicra/ (push)
とvirtual branchをclone。
「掲示板を起動」ボタンを押した後、URLはhttp://localhost:3000/loginに遷移しますが、
Cannot GET /loginと表示されます。

**Comment by masakura** [comment]
バッチグーっす!

Markdown の書き方も覚えると役に立つと思いますよ。こんな感じで書くと、見やすいです。

```
$ git clone https://github.com/begicra/begicra/
$ git checkout virtual
$ npm install
```
